{% set name = "cad_to_dagmc" %}
{% set version = "0.8.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5487f3172f8b8bd765492c6748bebc9baa295e86f30a673d1f420136efa6ae78

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0


requirements:
  host:
    - python {{ python_min }}
    - setuptools >=65.4.0
    - setuptools-scm >=7.0.5
    - pip
  run:
    - python >={{ python_min }}
    - moab >=5.3.0
    - gmsh
    - python-gmsh
    - cadquery >=2.4.0
    - numpy <=1.26.4
    - ocp >=7.7.2
    - trimesh
    - networkx

test:
  imports:
    - cad_to_dagmc
  requires:
    - python {{ python_min }}
    - pip
    - pytest
  source_files:
    - tests
  commands:
    - pytest tests

about:
  home: https://github.com/fusion-energy/cad_to_dagmc
  summary: 'Converts CAD geometry to a DAGMC h5m file'
  description: |
    Convert CAD geometry (STP files) or CadQuery assemblies to DAGMC h5m files
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - shimwell
