{% set name = "cad_to_dagmc" %}
{% set version = "0.11.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c5d625250027da0b00f4f1d44540871e6f2b5ed53c2394040078857a324f2490

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1


requirements:
  host:
    - python {{ python_min }}
    - setuptools >=65.4.0
    - setuptools-scm >=7.0.5
    - pip
  run:
    - python >={{ python_min }}
    - cadquery >=2.6.0
    - numpy <=1.26.4
    - gmsh
    - python-gmsh  
    - h5py
    # TODO consider moving from a noarch package so that we can do
    # - moab >=5.3.0  [not win]
    # this is not possible with a noarch package
    # Therefore moab backend is removed as it prevents installation on windows
    # - moab >=5.3.0 
    - ocp >=7.7.2
    - trimesh
    - networkx

test:
  imports:
    - cad_to_dagmc
  requires:
    - python {{ python_min }}
    - pip
    - pytest
  source_files:
    - tests
  commands:
    - pytest tests/test_file_creation.py
    # TODO add this test but it requires openmc
    # this test needs openmc
    #- pytest tests/test_get_volumes.py
    - pytest tests/test_h5m_in_transport.py
    - pytest tests/test_loading_from_file_vs_shape_object.py
    # TODO add this test but it requires assembly-mesh-plugio - 
    # if assembly-mesh-plugio gets packaged on conda-forge test all file
    # pytest tests/test_mesh_to_dagmc.py
    - pytest tests/test_python_api.py
    - pytest tests/test_version.py

about:
  home: https://github.com/fusion-energy/cad_to_dagmc
  summary: 'Converts CAD geometry to a DAGMC h5m file'
  description: |
    Convert CAD geometry (STP files) or CadQuery assemblies to DAGMC h5m files
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - shimwell
